version: '3'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - ORDER_SERVICE_URL=http://order-service:3001
      - PAYMENT_SERVICE_URL=http://payment-service:3002
      - MENU_SERVICE_URL=http://menu-service:3003
      - INVENTORY_SERVICE_URL=http://inventory-service:3004
      - CUSTOMER_SERVICE_URL=http://customer-service:3005
    depends_on:
      - order-service
      - payment-service
      - menu-service
      - inventory-service
      - customer-service

  order-service:
    build: ./order-services
    ports:
      - "3001:3001"

  payment-service:
    build: ./payment-services
    ports:
      - "3002:3002"

  menu-service:
    build: ./menu-services
    ports:
      - "3003:3003"

  inventory-service:
    build: ./inventory-services
    ports:
      - "3004:3004"

  customer-service:
    build: ./customer-services
    ports:
      - "3005:3005" 