version: '3'

services:
  api-gateway:
    image: husnain239/cafe-management-api-gateway:latest
    ports:
      - "3000:3000"
    environment:
      - ORDER_SERVICE_URL=http://order-service:3001
      - PAYMENT_SERVICE_URL=http://payment-service:3002
      - MENU_SERVICE_URL=http://menu-service:3003
      - INVENTORY_SERVICE_URL=http://inventory-service:3004
      - CUSTOMER_SERVICE_URL=http://customer-service:3005
    depends_on:
      - order-service
      - payment-service
      - menu-service
      - inventory-service
      - customer-service
    restart: always

  order-service:
    image: husnain239/cafe-management-order-services:latest
    ports:
      - "3001:3001"
    restart: always

  payment-service:
    image: husnain239/cafe-management-payment-services:latest
    ports:
      - "3002:3002"
    restart: always

  menu-service:
    image: husnain239/cafe-management-menu-services:latest
    ports:
      - "3003:3003"
    restart: always

  inventory-service:
    image: husnain239/cafe-management-inventory-services:latest
    ports:
      - "3004:3004"
    restart: always

  customer-service:
    image: husnain239/cafe-management-customer-services:latest
    ports:
      - "3005:3005"
    restart: always 